name: joseph_prueba
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^7.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/